#!/usr/bin/env bash

gsout="/tmp/gswrapper.gamescope.out"

gamescope_opts=""
command=""

while [[ $# -gt 0 ]]; do
  if [ "$1" == "--" ]; then
    shift
    command="$*"
    break
  fi
  gamescope_opts+=" $1"
  shift
done

gamescope $gamescope_opts &>"$gsout" &
gs_pid=$!

while read -r line; do
  display=$(echo "$line" | sed -nE 's/^.*Starting Xwayland on :([0-9]+).*$/\1/p')
  if [ -n "$display" ]; then
    break
  fi
done < <(tail -f "$gsout")

DISPLAY=":$display" eval "$command"
kill "$gs_pid"
